const data = {
    keys: [
      {
        id: "7",
        value: "7",
        label: "7",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-end border-bottom",
      },
      {
        id: "8",
        value: "8",
        label: "8",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-end border-bottom",
      },
      {
        id: "9",
        value: "9",
        label: "9",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-bottom",
      },
      {
        id: "4",
        value: "4",
        label: "4",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-end border-bottom",
      },
      {
        id: "5",
        value: "5",
        label: "5",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-end border-bottom",
      },
      {
        id: "6",
        value: "6",
        label: "6",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-bottom",
      },
      {
        id: "1",
        value: "1",
        label: "1",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-end border-bottom",
      },
      {
        id: "2",
        value: "2",
        label: "2",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-end border-bottom",
      },
      {
        id: "3",
        value: "3",
        label: "3",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-bottom",
      },
      {
        id: "10",
        value: "RESET",
        label: "RESET",
        // label: <i className="fa-solid fa-delete-left"></i>,
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-end",
      },
      {
        id: "0",
        value: "0",
        label: "0",
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-end",
      },
      {
        id: "11",
        value: "DELETE",
        label: "DELETE",
        // label: <i class="fa-solid fa-trash-can"></i>,
        class: "col-3 p-1",
        classBtn: "mx-auto px-3",
        border: "border-0",
      },
    ],
  };
  export default data;